// <auto-generated />
using System;
using Api.Service.Stock.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Service.Stock.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20221002173904_nova tabela itensCompra")]
    partial class novatabelaitensCompra
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Api.Service.Stock.Models.ItensCompra", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProdutoUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Quantidade")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Uid");

                    b.HasIndex("ProdutoUid");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("ItensCompra");
                });

            modelBuilder.Entity("Api.Service.Stock.Models.Produto", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Uid");

                    b.HasIndex("Estoque");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Api.Service.Stock.Models.ItensCompra", b =>
                {
                    b.HasOne("Api.Service.Stock.Models.Produto", "DbProduto")
                        .WithMany("DbItensCompraModel")
                        .HasForeignKey("ProdutoUid")
                        .IsRequired();

                    b.Navigation("DbProduto");
                });

            modelBuilder.Entity("Api.Service.Stock.Models.Produto", b =>
                {
                    b.Navigation("DbItensCompraModel");
                });
#pragma warning restore 612, 618
        }
    }
}
